name: KillStreak
version: ${project.version}
main: me.pljr.killstreak.KillStreak
api-version: 1.16
authors: [9hx]
description: Simple plugin for counting kills of players.
commands:
  killstreak:
    description: Main command.
