name: KillStreak
version: ${project.version}
main: me.pljr.killstreak.KillStreak
api-version: 1.13
authors: [9hx]
description: Simple plugin for counting kills of players.
depend: [PLJRApi-Spigot]
commands:
  killstreak:
    description: Main command.
